development:
  adapter: postgresql
  encoding: unicode
  database: vh_medicines
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: vh_medicines
  username: postgres
  password: postgres
