# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ff7ba03a250af91ed4074ba1de6739706f95eba21ec468cf7addfe9ca35ea6b2ab21b731ad5f8380d2ef5ce061f245297932065ff745eab87c02f846d034faf

test:
  secret_key_base: 028ab7fc3b06b893c861c26338b74729da3dbac3ffe70e21909968ad4ab7af0b4b1b549451dd0587be9687c025b0dbfdeb51f05abcf208a781f5b3793cd01573

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
